"""Parse a TradingView "Alerts Log" CSV export into `Alert` records.

The export has six columns: Alert ID, Ticker, Name, Description, Time,
Webhook status. The `Ticker` column looks like `EXCHANGE:SYMBOL` or
`EXCHANGE:SYMBOL, TIMEFRAME` (the timeframe suffix shows up for
volume/trendline/strategy alerts that are tied to a specific chart
resolution). The `Description` column is free text generated by whichever
TradingView alert condition fired; we classify it into an `AlertType` and
pull out the numeric level when there is one.
"""

from __future__ import annotations

import csv
import re
from datetime import datetime, timezone
from pathlib import Path

from tv_alerts.models import Alert, AlertType

_TICKER_RE = re.compile(r"^(?:([A-Z_]+):)?([A-Za-z0-9.\-]+)(?:,\s*(\S+))?$")

# "GOOG Crossing 350.28" / "MKL Crossing 2,003.72"
_PRICE_CROSS_RE = re.compile(r"Crossing\s+([\d,]+\.?\d*)\s*$")

# "SUI, 1D Crossing trendline" / "DEO, 1D Crossing Trend Line"
_TRENDLINE_RE = re.compile(r"Crossing\s+trend\s*line", re.IGNORECASE)

# "Volume Crossing 4.5<mangled-space>M on ACHC, 1D" / "Volume Crossing Up 4<sp>M on UDR, 1D"
# The number/unit separator is sometimes a mis-decoded narrow no-break space,
# so match on "junk that isn't a digit or letter" rather than literal whitespace.
_VOLUME_CROSS_RE = re.compile(
    r"^Volume Crossing(?: Up)?\s+([\d,]+\.?\d*)[^0-9A-Za-z]*([MKB])\b", re.IGNORECASE
)

_MA_STRATEGY_RE = re.compile(r"Moving Average", re.IGNORECASE)

_UNIT_MULTIPLIER = {"K": 1e3, "M": 1e6, "B": 1e9}


def _parse_number(text: str) -> float:
    return float(text.replace(",", ""))


def _split_ticker(raw_ticker: str) -> tuple[str, str, str | None]:
    """Split "BATS:GOOG" or "BATS:SUI, 1D" into (exchange, symbol, timeframe)."""
    match = _TICKER_RE.match(raw_ticker.strip())
    if not match:
        return "", raw_ticker.strip(), None
    exchange, symbol, timeframe = match.groups()
    return exchange or "", symbol, timeframe


def classify_description(description: str) -> tuple[AlertType, float | None]:
    """Return (alert_type, level) for a Description cell."""
    volume_match = _VOLUME_CROSS_RE.match(description)
    if volume_match:
        value = _parse_number(volume_match.group(1))
        unit = volume_match.group(2).upper()
        return AlertType.VOLUME_CROSS, value * _UNIT_MULTIPLIER[unit]

    if _MA_STRATEGY_RE.search(description):
        return AlertType.MA_STRATEGY, None

    if _TRENDLINE_RE.search(description):
        return AlertType.TRENDLINE_CROSS, None

    price_match = _PRICE_CROSS_RE.search(description)
    if price_match:
        return AlertType.PRICE_CROSS, _parse_number(price_match.group(1))

    return AlertType.OTHER, None


def parse_alerts(csv_path: str | Path) -> list[Alert]:
    alerts: list[Alert] = []
    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            raw_ticker = (row.get("Ticker") or "").strip()
            description = (row.get("Description") or "").strip()
            time_str = (row.get("Time") or "").strip()
            if not raw_ticker or not time_str:
                continue

            exchange, symbol, timeframe = _split_ticker(raw_ticker)
            alert_type, level = classify_description(description)
            alert_time = datetime.strptime(time_str, "%Y-%m-%dT%H:%M:%SZ").replace(
                tzinfo=timezone.utc
            )

            alerts.append(
                Alert(
                    alert_id=(row.get("Alert ID") or "").strip(),
                    exchange=exchange,
                    symbol=symbol,
                    timeframe=timeframe,
                    description=description,
                    time=alert_time,
                    alert_type=alert_type,
                    level=level,
                    raw_ticker=raw_ticker,
                )
            )
    return alerts
