/**
 * Parse a TradingView "Alerts Log" CSV export into `Alert` records.
 *
 * The export has six columns: Alert ID, Ticker, Name, Description, Time,
 * Webhook status. The `Ticker` column looks like `EXCHANGE:SYMBOL` or
 * `EXCHANGE:SYMBOL, TIMEFRAME` (the timeframe suffix shows up for
 * volume/trendline/strategy alerts that are tied to a specific chart
 * resolution). The `Description` column is free text generated by
 * whichever TradingView alert condition fired; we classify it into an
 * `AlertType` and pull out the numeric level when there is one.
 */

import { readFileSync } from "node:fs";
import { parse as parseCsv } from "csv-parse/sync";
import type { Alert, AlertType } from "./models.js";

const TICKER_RE = /^(?:([A-Z_]+):)?([A-Za-z0-9.-]+)(?:,\s*(\S+))?$/;

// "GOOG Crossing 350.28" / "MKL Crossing 2,003.72" / "ACI Crossing Up 14.10"
// The Up/Down variants state a direction outright, which is better than the
// side-inference-from-live-price that addAlert otherwise has to do.
const PRICE_CROSS_RE = /Crossing\s+(?:(Up|Down)\s+)?([\d,]+\.?\d*)\s*$/i;

// "UNP Crossing 277.50 AND Volume Crossing 3 M on UNP, 1D" - a compound
// price-AND-volume alert, which maps onto StaticAlert + volumeCondition.
const COMPOUND_PRICE_VOLUME_RE =
  /Crossing\s+([\d,]+\.?\d*)\s+AND\s+Volume Crossing(?:\s+Up)?\s+([\d,]+\.?\d*)[^0-9A-Za-z]*([MKB])\b/i;

// "AGNC, 1D Exiting rectangle" - a drawing/pattern alert. Nothing numeric to
// act on, but worth naming rather than silently landing in "other".
const PATTERN_RE = /\b(?:Entering|Exiting)\s+(?:rectangle|triangle|channel|wedge|flag)\b/i;

// "SUI, 1D Crossing trendline" / "DEO, 1D Crossing Trend Line"
const TRENDLINE_RE = /Crossing\s+trend\s*line/i;

// "Volume Crossing 4.5<mangled-space>M on ACHC, 1D" / "Volume Crossing Up 4<sp>M on UDR, 1D"
// The number/unit separator is sometimes a mis-decoded narrow no-break space,
// so match on "junk that isn't a digit or letter" rather than literal whitespace.
const VOLUME_CROSS_RE = /^Volume Crossing(?: Up)?\s+([\d,]+\.?\d*)[^0-9A-Za-z]*([MKB])\b/i;

const MA_STRATEGY_RE = /Moving Average/i;

const UNIT_MULTIPLIER: Record<string, number> = { K: 1e3, M: 1e6, B: 1e9 };

function parseNumber(text: string): number {
  return parseFloat(text.replace(/,/g, ""));
}

function splitTicker(rawTicker: string): { exchange: string; symbol: string; timeframe: string | null } {
  const match = TICKER_RE.exec(rawTicker.trim());
  if (!match) {
    return { exchange: "", symbol: rawTicker.trim(), timeframe: null };
  }
  const [, exchange, symbol, timeframe] = match;
  return { exchange: exchange ?? "", symbol, timeframe: timeframe ?? null };
}

export interface Classification {
  alertType: AlertType;
  level: number | null;
  /** Set when the alert states its own direction ("Crossing Up 14.10"). */
  direction: "up" | "down" | null;
  /** Share count for the volume half of a compound price-AND-volume alert. */
  andVolume: number | null;
}

export function classifyDescription(description: string): Classification {
  const volumeMatch = VOLUME_CROSS_RE.exec(description);
  if (volumeMatch) {
    const value = parseNumber(volumeMatch[1]);
    const unit = volumeMatch[2].toUpperCase();
    return { alertType: "volume_cross", level: value * UNIT_MULTIPLIER[unit], direction: null, andVolume: null };
  }

  if (MA_STRATEGY_RE.test(description)) {
    return { alertType: "ma_strategy", level: null, direction: null, andVolume: null };
  }

  if (TRENDLINE_RE.test(description)) {
    return { alertType: "trendline_cross", level: null, direction: null, andVolume: null };
  }

  if (PATTERN_RE.test(description)) {
    return { alertType: "pattern", level: null, direction: null, andVolume: null };
  }

  // Checked before the plain price pattern: a compound description ends with
  // the chart's "on TICKER, 1D" suffix, so the end-anchored price regex would
  // miss it entirely and drop the alert. Classified as price_cross so the
  // breakout pipeline still judges it on its price level.
  const compoundMatch = COMPOUND_PRICE_VOLUME_RE.exec(description);
  if (compoundMatch) {
    return {
      alertType: "price_cross",
      level: parseNumber(compoundMatch[1]),
      direction: null,
      andVolume: parseNumber(compoundMatch[2]) * UNIT_MULTIPLIER[compoundMatch[3].toUpperCase()],
    };
  }

  const priceMatch = PRICE_CROSS_RE.exec(description);
  if (priceMatch) {
    const direction = priceMatch[1] ? (priceMatch[1].toLowerCase() as "up" | "down") : null;
    return { alertType: "price_cross", level: parseNumber(priceMatch[2]), direction, andVolume: null };
  }

  return { alertType: "other", level: null, direction: null, andVolume: null };
}

export function parseAlerts(csvPath: string): Alert[] {
  const content = readFileSync(csvPath, "utf-8");
  const records: Record<string, string>[] = parseCsv(content, {
    columns: true,
    bom: true,
    skip_empty_lines: true,
  });

  const alerts: Alert[] = [];
  for (const row of records) {
    const rawTicker = (row["Ticker"] ?? "").trim();
    const description = (row["Description"] ?? "").trim();
    const timeStr = (row["Time"] ?? "").trim();
    if (!rawTicker || !timeStr) {
      continue;
    }

    const { exchange, symbol, timeframe } = splitTicker(rawTicker);
    const { alertType, level } = classifyDescription(description);
    const time = new Date(timeStr);

    alerts.push({
      alertId: (row["Alert ID"] ?? "").trim(),
      exchange,
      symbol,
      timeframe,
      description,
      time,
      alertType,
      level,
      rawTicker,
    });
  }
  return alerts;
}
